# Terraform backend configuration for dev
# Generated by setup-backend.sh on Wed Oct 22 21:38:44 CEST 2025

bucket         = "adas-carla-terraform-state-715841366502"
key            = "environments/dev/terraform.tfstate"
region         = "eu-west-1"
dynamodb_table = "adas-carla-terraform-locks"
encrypt        = true
